### PR TITLE
Jan 2019 update

### PR DESCRIPTION
**Pull request by crpietschmann**

### CODE REVIEW

**Comment by RickShahid** [comment]
From our previous discussion in regard to the updates for this workshop, I thought the intent was to move away from using Visual Studio in favor of using the Azure management portal for the lab work?

**Comment by cloudmelon** [comment]
> From our previous discussion in regard to the updates for this workshop, I thought the intent was to move away from using Visual Studio in favor of using the Azure management portal for the lab work?

It would a more open way if we encourage users to use Azure portal instead of visual studio in favor of plugins / extensions, in that case, we should align the guidance.

**Comment by RickShahid** [comment]
I agree that we should have the guidance and the hands-on lab geared toward using the Azure portal for Functions, Logic App, etc. That'll make the workshop more consumable for non-VS / .NET developers.

**Comment by shigeyf** [comment]
One comment to the logic app workflow:
Maybe it would be good to use callback URL in ‘Upload video and index’ action without until and delay loop. More simpler workflow and less action cost. See the article below in detail.

https://azure.microsoft.com/en-us/blog/logic-apps-flow-connectors-will-make-automating-video-indexer-simpler-than-ever/

**Comment by DawnmarieDesJardins** [comment]
@mwasham @crpietschmann 
Hi gentlemen,
We have lead sign off to finalize this update.  Please make final updates/edits, close open issues and assigned it to me when it's ready for QC/merge.

**Comment by crpietschmann** [comment]
> One comment to the logic app workflow:
> Maybe it would be good to use callback URL in ‘Upload video and index’ action without until and delay loop. More simpler workflow and less action cost. See the article below in detail.
> 
> https://azure.microsoft.com/en-us/blog/logic-apps-flow-connectors-will-make-automating-video-indexer-simpler-than-ever/

This is a good idea, however the "Until" loop is currently being used so the app can have an updated status of the progress of the video processing to display to the user; ala "percent complete" style. This is the reason the loop is implemented in this lab.

**Comment by crpietschmann** [comment]
> From our previous discussion in regard to the updates for this workshop, I thought the intent was to move away from using Visual Studio in favor of using the Azure management portal for the lab work?

Yes, the lab has been updated now to use the Azure Portal for the Logic App and the Azure Function; rather than Visual Studio.

**Comment by crpietschmann** [comment]
All comments and issues for this have been addressed. This is ready for QC/Merge process.

**Pull request merged**
